all = dasum.o daxpy.o dcopy.o ddot.o dgebak.o dgebal.o dgeco.o dgeev.o dgefa.o dgehd2.o dgehrd.o dgemm.o dgemv.o dger.o dgesl.o dhseqr.o dlabad.o dlacpy.o dladiv.o dlaexc.o dlahqr.o dlahr2.o dlaln2.o dlamch.o dlange.o dlanv2.o dlapy2.o dlaqr0.o dlaqr1.o dlaqr2.o dlaqr3.o dlaqr4.o dlaqr5.o dlarf.o dlarfb.o dlarfg.o dlarft.o dlarfx.o dlartg.o dlascl.o dlaset.o dlassq.o dlasy2.o dnrm2.o dorg2r.o dorghr.o dorgqr.o drot.o dscal.o dswap.o dtrevc.o dtrexc.o dtrmm.o dtrmv.o idamax.o lsame.o xerbla.o ieeeck.o ilaenv.o iparmq.o

ieeeck.o: ieeeck.f
	$(FC) -c ieeeck.f

ilaenv.o: ilaenv.f
	$(FC) -c ilaenv.f

iparmq.o: iparmq.f
	$(FC) -c iparmq.f

dasum.o: dasum.f
	$(FC) -c dasum.f

daxpy.o: daxpy.f
	$(FC) -c daxpy.f

dcopy.o: dcopy.f
	$(FC) -c dcopy.f

ddot.o: ddot.f
	$(FC) -c ddot.f

dgebak.o: dgebak.f
	$(FC) -c dgebak.f

dgebal.o: dgebal.f
	$(FC) -c dgebal.f

dgeco.o: dgeco.f
	$(FC) -c dgeco.f

dgeev.o: dgeev.f
	$(FC) -c dgeev.f

dgefa.o: dgefa.f
	$(FC) -c dgefa.f

dgehd2.o: dgehd2.f
	$(FC) -c dgehd2.f

dgehrd.o: dgehrd.f
	$(FC) -c dgehrd.f

dgemm.o: dgemm.f
	$(FC) -c dgemm.f

dgemv.o: dgemv.f
	$(FC) -c dgemv.f

dger.o: dger.f
	$(FC) -c dger.f

dgesl.o: dgesl.f
	$(FC) -c dgesl.f

dhseqr.o: dhseqr.f
	$(FC) -c dhseqr.f

dlabad.o: dlabad.f
	$(FC) -c dlabad.f

dlacpy.o: dlacpy.f
	$(FC) -c dlacpy.f

dladiv.o: dladiv.f
	$(FC) -c dladiv.f

dlaexc.o: dlaexc.f
	$(FC) -c dlaexc.f

dlahqr.o: dlahqr.f
	$(FC) -c dlahqr.f

dlahr2.o: dlahr2.f
	$(FC) -c dlahr2.f

dlaln2.o: dlaln2.f
	$(FC) -c dlaln2.f

dlamch.o: dlamch.f
	$(FC) -c dlamch.f

dlange.o: dlange.f
	$(FC) -c dlange.f

dlanv2.o: dlanv2.f
	$(FC) -c dlanv2.f

dlapy2.o: dlapy2.f
	$(FC) -c dlapy2.f

dlaqr0.o: dlaqr0.f
	$(FC) -c dlaqr0.f

dlaqr1.o: dlaqr1.f
	$(FC) -c dlaqr1.f

dlaqr2.o: dlaqr2.f
	$(FC) -c dlaqr2.f

dlaqr3.o: dlaqr3.f
	$(FC) -c dlaqr3.f

dlaqr4.o: dlaqr4.f
	$(FC) -c dlaqr4.f

dlaqr5.o: dlaqr5.f
	$(FC) -c dlaqr5.f

dlarf.o: dlarf.f
	$(FC) -c dlarf.f

dlarfb.o: dlarfb.f
	$(FC) -c dlarfb.f

dlarfg.o: dlarfg.f
	$(FC) -c dlarfg.f

dlarft.o: dlarft.f
	$(FC) -c dlarft.f

dlarfx.o: dlarfx.f
	$(FC) -c dlarfx.f

dlartg.o: dlartg.f
	$(FC) -c dlartg.f

dlascl.o: dlascl.f
	$(FC) -c dlascl.f

dlaset.o: dlaset.f
	$(FC) -c dlaset.f

dlassq.o: dlassq.f
	$(FC) -c dlassq.f

dlasy2.o: dlasy2.f
	$(FC) -c dlasy2.f

dnrm2.o: dnrm2.f
	$(FC) -c dnrm2.f

dorg2r.o: dorg2r.f
	$(FC) -c dorg2r.f

dorghr.o: dorghr.f
	$(FC) -c dorghr.f

dorgqr.o: dorgqr.f
	$(FC) -c dorgqr.f

drot.o: drot.f
	$(FC) -c drot.f

dscal.o: dscal.f
	$(FC) -c dscal.f

dswap.o: dswap.f
	$(FC) -c dswap.f

dtrevc.o: dtrevc.f
	$(FC) -c dtrevc.f

dtrexc.o: dtrexc.f
	$(FC) -c dtrexc.f

dtrmm.o: dtrmm.f
	$(FC) -c dtrmm.f

dtrmv.o: dtrmv.f
	$(FC) -c dtrmv.f

idamax.o: idamax.f
	$(FC) -c idamax.f

lsame.o: lsame.f
	$(FC) -c lsame.f

xerbla.o: xerbla.f
	$(FC) -c xerbla.f


clean:
	rm -f *.o
